### ISSUE TITLE
Empty window at startup under macOS 15

### ISSUE THREAD

**Issue by det-box** [DamascenoRafael/reminders-menubar#219] opened 2024-09-18 18:18 UTC
Under macOS 15, an empty window appears on startup.

<img width="900" alt="Bildschirmfoto 2024-09-18 um 20 17 04" src="https://github.com/user-attachments/assets/902e1d16-0e86-403e-936f-5258e4e1d1d8">

**Comment by DamascenoRafael** [comment] 2024-09-20 03:20
Duplicate of #204

**Closed by DamascenoRafael** 2024-09-20 03:20 UTC
