### ISSUE TITLE
1.16 seems to not sync information about what lists should appear, menu bar icon

### ISSUE THREAD

**Issue by andylin2004** [DamascenoRafael/reminders-menubar#124] opened 2023-04-02 18:20 UTC
After updating from the last 1.15 build to the new 1.16 build via brew, I seem to have some issues with settings I have previously configured not loading at all. I'm not too sure if this is the fault of having the app signed now or not, but its a bit annoying

**Comment by andylin2004** [comment] 2023-04-02 18:24
Changing the settings for the app, quitting it, and then relaunching the app can help, but still an annoying way to live.

**Comment by DamascenoRafael** [comment] 2023-04-03 12:45
I'm sorry to hear that, the settings may have been lost because the app's bundle-id changed between v1.15 and v1.16.
I'll add a note in the release to clarify this issue. This should not happen for future versions.

After you change the settings in v1.16 those new settings are kept even if you quit and reopen the app, right?

I don't know if I understand your last message, does something different happen if you quit and reopen the app?

**Comment by andylin2004** [comment] 2023-04-03 12:50
The changes in settings do take into effect after I close and repopen the app. They do not occur immediately as on previous builds.

**Comment by DamascenoRafael** [comment] 2023-04-03 13:01
The settings were reset when you opened v1.16, but after closing and reopening the app, the settings from previous versions reappeared? or did you need to do this due to another issue?

Please add an example if applicable so I can investigate. It was expected that when opening v1.16 the settings could be reset, but after that any new settings would be kept, without the need to close and reopen the app.

**Comment by andylin2004** [comment] 2023-04-03 13:44
When I opened 1.16 for the first time since updating it via brew, the settings were reset. After quitting and reopening the app after the first launch, it failed to load the previous version's settings and would just take on the new settings that I had setted  up on initial launch. Any other changes in settings (eg changing menu bar icon) also required the app to be closed and restarted.

**Comment by DamascenoRafael** [comment] 2023-04-04 03:17
Thanks for reporting the issue. Now I realized what is happening.
I'm already aware of the cause of the problem and should be able to release a fix tomorrow.

**Closed** 2023-04-05 00:36 UTC
Labels: bug

**Comment by DamascenoRafael** [comment] 2023-04-05 01:39
@andylin2004 please check release v1.16.1 📦 
Let me know if the behavior is now as expected and if you find any other issues.

**Comment by andylin2004** [comment] 2023-04-05 12:20
Seems to be working now.
