### ISSUE TITLE
Today count not displayed

### ISSUE THREAD

**Issue by jmuheim** [DamascenoRafael/reminders-menubar#69] opened 2022-09-26 08:27 UTC
Although I have checked the option **Show today count in the menu bar**, I don't see it:

![CleanShot 2022-09-26 at 10 23 43@2x](https://user-images.githubusercontent.com/1814983/192229127-fdc5ab48-b077-4d0f-a766-b33de3aefc4f.png)

How to fix? This is a key feature for me.

**Comment by DamascenoRafael** [comment] 2022-09-26 12:29
Hello @jmuheim. Thanks for the feedback.
In the image you sent the reminder is due tomorrow.
The menu bar counter displays only the number of reminders that are due today.
Can you add a reminder with a due date for today and test the behavior?

**Comment by DamascenoRafael** [comment] 2022-09-29 02:15
Thanks @jmuheim. Closing this since it's not a bug.
Please feel free to open another issue if you find any bugs or have suggestions for improvement.

**Closed by DamascenoRafael** 2022-09-29 02:15 UTC
