### ISSUE TITLE
Persist list filtering settings

### ISSUE THREAD

**Issue by scottrobertson** [DamascenoRafael/reminders-menubar#35] opened 2021-11-06 13:12 UTC
The dropdown (bottom left) that filters lists is awesome, however it does not persist when the app is restarted.

These settings should be saved somewhere and persist across sessions.

**Comment by scottrobertson** [comment] 2021-11-06 13:14
Also @DamascenoRafael, you should enable GitHub Sponsorship if you can. Would love to contribute a little to help this development :)

**Comment by DamascenoRafael** [comment] 2022-02-28 03:24
Hey, @scottrobertson. 
The filtered lists are saved in the user preferences and should persist when the app is restarted. The only exception is when no list is selected, in which case when restarting the app all lists appear selected. This was designed to prevent the app from opening and not showing any lists, but this was before the _Upcoming Reminders_ option. 
Can you tell me if this is the situation that is happening to you (no list selected and then when the app is restarted all lists appear selected)?

Maybe we can remove this situation now that there is an option for _Upcoming Reminders_, maybe the user always wants to see only this option (and no list).

If the problem is occurring in a different situation let me know so we can investigate further.

About sponsors, thanks for the suggestion!!
I applied to GitHub Sponsors but I'm still pending. 😞  
I'm looking at options like buymeacoffee and ko-fi.

**Comment by DamascenoRafael** [comment] 2022-03-08 00:48
@scottrobertson, waiting for your feedback so we can try to resolve this.

**Comment by DamascenoRafael** [comment] 2022-06-14 04:21
Hey, @scottrobertson. I'm closing this issue since it should be fixed in the latest version (1.7.1) 📦 
Let me know if you have any issues so we can investigate further.

**Closed by DamascenoRafael** 2022-06-14 04:21 UTC
