### ISSUE TITLE
Sort by due date

### ISSUE THREAD

**Issue by gferreroferri** [DamascenoRafael/reminders-menubar#12] opened 2021-02-26 10:01 UTC
Add an option to sort by due date, instead of grouping by lists

**Comment by DamascenoRafael** [comment] 2021-02-28 19:28
Good idea!! 👏 

I don't know exactly how you imagined it, but since not every reminder has a due date, I thought of a list of "Upcoming reminders" at the beginning with only reminders that have a due date (regardless of the list/calendar).

Perhaps in this list there could be an option to show only the reminders for the day, week, month or all (as long as it has a due date).

Can you tell me if you imagined anything other than that?

Without thinking about a list of "Upcoming reminders" I don't know exactly how we could order mixed lists of reminders with and without a due date.

**Comment by gferreroferri** [comment] 2021-02-28 19:32
There could be an option to show today’s due or this week’s due for instance on the top. Ore one section for the ones with due date ant another for the ones with no due date

**Comment by DamascenoRafael** [comment] 2021-03-07 20:42
@gferreroferri But this split into two lists (reminders with due date and no due date) would be helpful to you? If you are interested we can think about it too.

At first what seems most necessary would be a list of upcoming reminders (or smart lists as discussed in #13).

Here's a picture of what I was working on:

<img width="412" alt="Screen Shot 2021-03-07 at 16 33 13" src="https://user-images.githubusercontent.com/9842644/110253647-335e2180-7f6a-11eb-874a-6d7ee96bb611.png">

In the top button it would be possible to change which reminders would be displayed:
But I think that these options could have an easier text to understand.

<img width="124" alt="Screen Shot 2021-03-07 at 16 46 00" src="https://user-images.githubusercontent.com/9842644/110253659-4a9d0f00-7f6a-11eb-8500-ec074044ad91.png">

What do you think so far?

**Comment by adamlurie** [comment] 2021-03-08 01:22
This is fantastic, @DamascenoRafael! This is exactly what I was thinking and would be very useful!

**Comment by DamascenoRafael** [comment] 2021-03-16 04:41
Great!! I made the following changes:

- I changed the options for the upcoming reminders to: "Today", "In a Week", "In a Month" and "All".

<img width="182" alt="Screen Shot 2021-03-15 at 21 54 12" src="https://user-images.githubusercontent.com/9842644/111240430-fcc37f00-85d9-11eb-86c7-111440b452f9.png">

- I added an option on the bottom left button to show or not the list of upcoming reminders.

<img width="248" alt="Screen Shot 2021-03-15 at 21 59 53" src="https://user-images.githubusercontent.com/9842644/111240436-0351f680-85da-11eb-934f-46e15e560455.png">

**Comment by DamascenoRafael** [comment] 2021-03-16 05:36
Some points that we can still think about:

1 - Reminders with due date continue to appear in lists (such as “Study” and “To Do”) even though they are appearing in the "Upcoming reminders" list.. I don't see this as a problem.

2 - In lists outside of "Upcoming reminders" the reminders appear sorted by their creation date (which can be applied to all reminders). As a result, reminders with due date may appear out of order according to their due dates in these lists. I'm still thinking about how to solve it.

**Comment by adamlurie** [comment] 2021-03-16 23:47
For 1: Agreed. I think this is standard for to do/reminder applications (at least it is in Todoist). This is the expected behavior.

For 2: "Creation date" is kind of arbitrary for sorting (basically, the random order I remembered the items in the list). What about: (1) items that have a priority applied, then (2) items with day/time, then (3) all other items. Thoughts, @DamascenoRafael?

**Comment by gferreroferri** [comment] 2021-03-18 07:05
1: wouldn't they appear doubled if the Upcoming and the list are both selected? In that case they should only show in Upcoming

2: I think they should appear by due date

**Comment by DamascenoRafael** [comment] 2021-03-19 01:21
@adamlurie I think it's a great idea!! I will try to organize this and also add the priority indication in the reminders.
A reminder with day/time can also have a priority so I think we can generalize this idea to:
(1) Reminders are ordered according to priority (high to none);
(2) Then, for each priority: (a) first the reminders with day/time (sorted by due date - the earliest date first) and then (b) the reminders without day/time (sorted by creation date - most recent first).

@gferreroferri in fact reminders with day/time may appear duplicated if "Upcoming Reminders" and the corresponding reminder list are selected. But I think that the user can be confused if the fact of displaying in "Upcoming Reminders" disappears with that item from the corresponding list.
To solve this I think it would be better to create a visualization like the smart list "Scheduled" from Apple's Reminders app (image below), where we are no longer concerned with the reminder list but only with its due date. What do you think?
It would be similar to keeping only "Upcoming Reminders" selected, but it could have a split by date. In addition, reminders without day/time would not appear.

<img width="534" alt="Screen Shot 2021-03-18 at 21 47 52" src="https://user-images.githubusercontent.com/9842644/111717089-24168800-8836-11eb-8e8a-4df7fa70346b.png">

**Comment by gferreroferri** [comment] 2021-03-19 06:49
Yes, that solution for Scheduled sounds good :)

**Comment by DamascenoRafael** [comment] 2021-03-31 03:07
Sorry for taking so long.
I'm a little busy these days so I released version 1.4.0 now with "Upcoming Reminders" 📦 
For the next versions we can create a visualization like the "Scheduled" smart list :)

**Comment by gferreroferri** [comment] 2021-03-31 04:28
wow, new release looks really good!

**Comment by DamascenoRafael** [comment] 2022-02-26 20:47
Closing this issue since the reminders are sorted according to the rules discussed here 📆 
If necessary, we can open a new issue about other sorting rules.

**Closed by DamascenoRafael** 2022-02-26 20:47 UTC
Labels: enhancement
